### ISSUE TITLE
accessibility issue, jiggly Friend computer is very annoying and distracting.

### ISSUE THREAD

**Issue by dosuserx** [OtherwiseJunk/ParanoiaPerfectEditionSystem-foundryvtt#35]
i have an issue with my eyes that makes jiggling stuff, like when the computer dice come up 6, like that make it difficult to read, which makes gming impossible until i erase the role to let my eyes read stuff. can i have the ability to turn that off. i am willing to make a edit of friend computers picture to have an alternative image instead of (or in addition to it if you don't have my eye problems). its becoming an obstacle to adding content.

**Comment by OtherwiseJunk** [comment]
I can disable the jiggling in a build I'll get out sometime tomorrow, likely in the evening

**Comment by OtherwiseJunk** [comment]
I've updated it so that instead of relying on an animation we use a different colored eye, it's not a perfect solution but it should at least allow GMs to quickly notice when the computer dice is rolled without a distracting animation:

![image](https://github.com/OtherwiseJunk/ParanoiaPerfectEditionSystem-foundryvtt/assets/4574230/d35f41e8-0c08-44de-834c-571368812b95)

It should be building now, and I'll push the results up at lunch (4 hours or so)

**Comment by OtherwiseJunk** [comment]
![image](https://github.com/OtherwiseJunk/ParanoiaPerfectEditionSystem-foundryvtt/assets/4574230/48b33743-9929-4caf-b0db-67bb31444700)

**Comment by OtherwiseJunk** [comment]
happy to help. Always nice to see folks are using this.

0.2.1 should fix your issue, so I'm closing this out. But if you have any other problems or feature requests for sure feel free to leave them here
