### ISSUE TITLE
confusion about abilities @aliases

### ISSUE THREAD

**Issue by dosuserx** [OtherwiseJunk/ParanoiaPerfectEditionSystem-foundryvtt#36]
I'm new to foundry macros but not macros generally. i didn't a bit reading thru the code looking for the ability names, the @str stuff so you can make macros. it says in the code that you can use @str and other stats for paranoia but can that but explained a bit more?

**Comment by OtherwiseJunk** [comment]
ha I think some of this is a leftover from when I copied the initial template; str is from the dnd template that they provide by default.

I'm not sure if the character stats are currently exposed in such a way that you can access them in macros, but it would be something like abilities.brains or in that vein if it does.

I can take a look into this later this evening and do some testing to see what is currently exposed, and if nothing is figure out the best approach for exposing these to macros so players can make their own rolling macros

**Comment by OtherwiseJunk** [comment]
It looks like you can do things like

`/roll (@brains.value+@chutzpah.skills.bluff.value)d6` currently, but that access method is a little clunky.

I can look into how easy it would be to setup aliases for these so you can just refer to @brains or @bluff

**Comment by OtherwiseJunk** [comment]
Ok, I have a test build where all the stats/skills are now rollable with an @name (all lowercase)

![image](https://github.com/OtherwiseJunk/ParanoiaPerfectEditionSystem-foundryvtt/assets/4574230/fbc9ec23-a0e1-49af-85a7-75b7070169c1)
![image](https://github.com/OtherwiseJunk/ParanoiaPerfectEditionSystem-foundryvtt/assets/4574230/bbeafe77-1204-49a7-a256-bf85f752f8ee)

for skills that have a space in the name (Alpha Complex) the @ would become `@alphacomplex`.

For the stats I'm going to add `@brn` `@chtz` `@mec` and `@vio` aliases as well.

the skills seems dicier, the names are longer but it's not immediately clear to me if players would expect say `@aplx`, or `@alpha`, or `@alp`, etc. 

Down the line I might change my mind on that if I can come up with a clever way of communicating it to players, but for now this should do a lot to simplify these macros hopefully.

**Comment by OtherwiseJunk** [comment]
https://github.com/OtherwiseJunk/ParanoiaPerfectEditionSystem-foundryvtt/releases/tag/v0.3.0

This should now be live on foundry, and I have all the added aliases listed in the release linked above. Let me know if this helps!

**Comment by OtherwiseJunk** [comment]
@dosuserx does this clean things up/make things more clear or are there any additional changes you were thinking of

**Comment by dosuserx** [comment]
this is perfect. sorry for spacing out, ive been focused on re-reading old content and writing but im about to start setting up for sess-zero soon and you've clear the hurdles for that.

**Comment by dosuserx** [comment]
...apart from security clearence. im not sure if i should ask you to set up a thing to track it and set initiative based on it, but im not sure what that would look like so im not gonna ask. id be happy to brainstorm about though. ive been trying to learn about macros but mods make making them real confusing.

**Comment by OtherwiseJunk** [comment]
@dosuserx I think I have a solution for this.

Going to be releasing a 0.4.0 version to make what I have available shortly.

I am now deriving security clearance from the actor name, assuming they meet the expected format of <AnyCharacters>-[R,O,Y,G,B,I,V]-<AnyCharacters>. Otherwise we assume they're infrared.

These value are available for use in macros, in case you have any other uses for them in mind. the variable names for this is either `@sec` or `@securityClearance`.

default (assumed infrared): 1
r: 2
...
v: 8

We are also using this value for the default """formula""" on initiative, so when you "roll" it'll just slot you in initiative based on your clearance (which is ultimately based on your characters name)
![image](https://github.com/OtherwiseJunk/ParanoiaPerfectEditionSystem-foundryvtt/assets/4574230/68e7a641-3a57-4d52-ad90-68fd47c4f3bc)
