### ISSUE TITLE
Can't Create Items

### ISSUE THREAD

**Issue by Nyogtha68** [OtherwiseJunk/ParanoiaPerfectEditionSystem-foundryvtt#50]
v.0.4.2
Foundry v11, Build 315
As the title suggests.  When ctrying to create an item you get this error message:
"Item validation error: Type may not be undefined."
The item creation window does not have an option for Type.
Here is the log showing the error.
![image](https://github.com/user-attachments/assets/71e11adc-1987-404f-9318-fc040e53f242)

**Comment by OtherwiseJunk** [comment]
Yeah this is a bit of a known issue. I don't have anything rigged up for items, and even if I did the character sheet currently wouldn't support them 😅 

Definitely something I want to work on improving though, thank you for the issue report!

**Comment by Nyogtha68** [comment]
No problem.  Thanks again.

**Comment by OtherwiseJunk** [comment]
@Nyogtha68 version 0.5.0, which I'll be rolling out shortly, should resolve this issue and introduce a pretty bare-bones equipment sheet.

Troubleshooters won't be able to currently add them to their sheet, but GMs can setup folders for players to use as their inventories in the short term.

Once it's available can you please confirm it resolves the issue for you?

**Comment by OtherwiseJunk** [comment]
With a quick testing on V11 I think the items can be created but the choices aren't validated properly.

I think the helper I'm using _might_ be v12 only? not positive, I plan to do some testing but I've marked the version as requiring v12 for now. Need to do some testing still to ensure it works fine on v12 test environments, and probably look at putting out a v11 fix in a 0.5.1 release or something.

**Comment by Nyogtha68** [comment]
Thank you for the update. Will check it out later and let you know.

**Comment by OtherwiseJunk** [comment]
0.5.1 should now allow you to create a simple item:

![image](https://github.com/user-attachments/assets/6df6ccb9-839d-4943-9c50-d685ac2bd8d2)

**Comment by Nyogtha68** [comment]
@OtherwiseJunk just one question :) What is the 'Assigned' checkbox for?

**Comment by OtherwiseJunk** [comment]
Glad it's working 🥳 I haven't heard anything about an official Foundry mod but I'd love to see what they would do regardless of who is working on it 👀 

The assigned checkbox is moooostly useless at this stage, but equipment has a concept of "Has this been assigned to the troubleshooter for a mission or is it their personal equipment".

Even though we don't have a way of assigning equipment to a character sheet yet, I wanted to keep that concept out there because people could use item folders in the short term to track equipment for a character.
