### ISSUE TITLE
Show success dice

### ISSUE THREAD

**Issue by JamesAlday** [OtherwiseJunk/ParanoiaPerfectEditionSystem-foundryvtt#52]
I started playing around with this myself but haven't had the time to devote to it lately, unfortunately.  I'd highly suggest taking a look at some Year Zero Engine games, which also uses a 'dice pool' mechanic.  

For instance, in the Alien RPG it uses custom "alien dice" and the roller shows a blank die face image on a failure: https://github.com/pwatson100/alienrpg/blob/master/module/YZEDiceRoller.js

**Comment by Actual-Z** [comment]
I made an implantation of paranoia perfect edition using Custom System Builder. It has functionality of showing success dice along with service group, items, .etc being implemented as items so they can be dragged onto character sheets. I don't know if that would help you at all since it's done in Custom System Builder but if you want to look at it you can. The custom system builder foundry page links to templates including mine (the only one listed there for Paranoia) or I could share the current json export because I haven't sent an update to the creator of CSB.

**Comment by OtherwiseJunk** [comment]
Got an MVP setup for this, just adding an accounting of the successes in the message for now.

![image](https://github.com/user-attachments/assets/374d3f8d-3c74-42c6-8c90-4781a2b96eec)
![image](https://github.com/user-attachments/assets/3d282b78-63aa-4720-b841-ed814298dcbe)


I also refactored rolling as part of this so it'll be a bit easier to jazz up the dice results down the line, but this should work for the short term.

**Comment by rafal-molotkiewicz** [comment]
Consider learning from Fallout 2d20 module. It counts successes, has a special die for the body part you hit, that can be used for a prototype of the Computer dice. And as a side note, it allows you to right-click a skill and select "roll using ___" for example Repair -> roll using Luck. Would fit very well the Paranoia and be faster than selecting things from drop-downs.

**Comment by OtherwiseJunk** [comment]
Yeah, I think ultimately the solution would be generating our own html to embed in a message instead of relying on Foundry's display dice results. I want to get this MVP I posted above out this week so games can at least not have to manually calculate successes but ultimately having the success dice/failure dice highlighted nicely in our own HTML embed would be the goal.

I'm a little less sure on the right click idea, I think it would be better to just launch a dialog of the dice roller when you click a skill/ability that lets you select the additional information that might be needed (equipment, "speed", and the corresponding skill/ability depending on which you clicked). 

I think if it was just skill/ability pairs the right click option would be fine, but it loses some of the actions characters might take.

**Comment by RemyAllegro** [comment]
Is there any reason you aren't using the count successes function built into foundry?
For example: 
/r (NODE)d6cs>=5 to get
![image](https://github.com/user-attachments/assets/984e9fd7-9d3a-4a7c-8625-9e1d7f74ae4d)

and for negative dice pools you can use
/r 2*(NODE)d6cs>=5)-(NODE)
![image](https://github.com/user-attachments/assets/27606bb3-63ab-47d1-907e-c86a6ed3f01e)

**Comment by OtherwiseJunk** [comment]
Yeah I think I was a bit over ambitious initially, I wanted to get some fancier displays for the dice rolling in general but I'm going to run with this short term instead. I've already not had as much time to work on this as I'd like so it's better to get this working and worry about prettier dice rolls later 😆

**Comment by OtherwiseJunk** [comment]
Version v0.6.0 is now available which implements @RemyAllegro's suggestion (Thanks!)

I also setup a workflow on github that should make releasing a bit easier for me so hopefully future updates can come a bit faster 😅
